services:
  stalwart:
    ports:
      - "${STALWART_BIND_ADDRESS:-0.0.0.0}:${STALWART_SMTP_PORT:-25}:25"
      - "${STALWART_BIND_ADDRESS:-0.0.0.0}:${STALWART_HTTPS_PORT:-443}:443"
      - "${STALWART_BIND_ADDRESS:-0.0.0.0}:${STALWART_SUBMISSIONS_TLS_PORT:-465}:465"
      - "${STALWART_BIND_ADDRESS:-0.0.0.0}:${STALWART_SUBMISSION_PORT:-587}:587"
      - "${STALWART_BIND_ADDRESS:-0.0.0.0}:${STALWART_IMAPS_PORT:-993}:993"
